"use strict";

/* =========================================================
   PINEWOOD: THE WOODS
   FILE 4 — CONTENT, AUDIO, CUTSCENES & FINAL SYSTEMS

   Works with:
   index.html
   game.js
   style.css
   ========================================================= */


/* =========================================================
   SHORTCUTS
   ========================================================= */

const PG = window.PinewoodGame;

const G = PG.Game;
const P = PG.Player;
const W = PG.World;
const enemies = PG.Animals;


/* =========================================================
   AUDIO ENGINE
   No audio files are required.
   Everything is generated by the browser.
   ========================================================= */

const AudioSystem = {

    context: null,
    master: null,
    ambience: null,
    ambienceGain: null,

    start() {

        if (!this.context) {

            const AudioContext =
                window.AudioContext ||
                window.webkitAudioContext;

            if (!AudioContext) return;

            this.context =
                new AudioContext();

            this.master =
                this.context.createGain();

            this.master.gain.value = 0.18;

            this.master.connect(
                this.context.destination
            );

        }

        if (
            this.context.state ===
            "suspended"
        ) {

            this.context.resume();

        }

        this.startAmbience();

    },


    tone(
        frequency,
        duration,
        type = "sine",
        volume = 0.08
    ) {

        if (!this.context) return;

        const osc =
            this.context.createOscillator();

        const gain =
            this.context.createGain();

        osc.type = type;

        osc.frequency.value =
            frequency;

        gain.gain.setValueAtTime(
            volume,
            this.context.currentTime
        );

        gain.gain.exponentialRampToValueAtTime(
            0.001,
            this.context.currentTime +
            duration
        );

        osc.connect(gain);
        gain.connect(this.master);

        osc.start();

        osc.stop(
            this.context.currentTime +
            duration
        );

    },


    noise(
        duration = 0.15,
        volume = 0.08
    ) {

        if (!this.context) return;

        const buffer =
            this.context.createBuffer(
                1,
                this.context.sampleRate *
                duration,
                this.context.sampleRate
            );

        const data =
            buffer.getChannelData(0);

        for (
            let i = 0;
            i < data.length;
            i++
        ) {

            data[i] =
                Math.random() * 2 - 1;

        }

        const source =
            this.context.createBufferSource();

        const gain =
            this.context.createGain();

        source.buffer = buffer;

        gain.gain.value =
            volume;

        source.connect(gain);
        gain.connect(this.master);

        source.start();

    },


    footstep() {

        this.tone(
            75,
            0.055,
            "triangle",
            0.035
        );

    },


    attack() {

        this.noise(
            0.09,
            0.08
        );

        this.tone(
            95,
            0.13,
            "sawtooth",
            0.045
        );

    },


    hit() {

        this.tone(
            65,
            0.12,
            "square",
            0.06
        );

        this.noise(
            0.08,
            0.05
        );

    },


    creature() {

        this.tone(
            48,
            0.7,
            "sawtooth",
            0.055
        );

        setTimeout(
            () => {

                this.tone(
                    31,
                    0.8,
                    "sawtooth",
                    0.045
                );

            },
            130
        );

    },


    scare() {

        this.tone(
            210,
            0.12,
            "sawtooth",
            0.06
        );

        setTimeout(
            () => {

                this.tone(
                    55,
                    0.5,
                    "sawtooth",
                    0.07
                );

            },
            100
        );

    },


    death() {

        this.tone(
            120,
            0.4,
            "triangle",
            0.05
        );

        setTimeout(
            () => {

                this.tone(
                    55,
                    0.8,
                    "sine",
                    0.035
                );

            },
            180
        );

    },


    startAmbience() {

        if (
            this.ambience
        ) return;

        this.ambience =
            setInterval(
                () => {

                    if (
                        G.mode !==
                        "explore"
                    ) return;

                    this.tone(
                        42 +
                        Math.random() * 18,
                        1.5,
                        "sine",
                        0.012
                    );

                },
                2400
            );

    }

};


/* =========================================================
   START AUDIO WHEN PLAYER STARTS
   ========================================================= */

const originalStartGame =
    window.startGame;

document.addEventListener(
    "click",
    () => {

        AudioSystem.start();

    },
    { once: true }
);


/* =========================================================
   EXTRA PLAYER DAMAGE SYSTEM
   ========================================================= */

function damagePlayer(amount) {

    P.health -= amount;

    P.health =
        Math.max(
            0,
            P.health
        );

    AudioSystem.hit();

    PG.updateHUD();

    if (
        P.health <= 0
    ) {

        playerDeath();

    }

}


/* =========================================================
   PLAYER DEATH
   ========================================================= */

function playerDeath() {

    G.mode =
        "dead";

    G.running =
        false;

    AudioSystem.death();

    const screen =
        document.getElementById(
            "deathScreen"
        );

    screen.style.display =
        "flex";

}


/* =========================================================
   RESTART
   ========================================================= */

document
    .getElementById(
        "restartButton"
    )
    .addEventListener(
        "click",
        restartGame
    );


function restartGame() {

    P.health =
        P.maxHealth;

    P.stamina =
        P.maxStamina;

    P.x = 2050;
    P.y = 1600;

    for (
        const enemy
        of enemies
    ) {

        enemy.defeated =
            false;

        enemy.active =
            true;

        enemy.health =
            enemy.maxHealth;

    }

    G.currentEnemy =
        null;

    G.battleOpen =
        false;

    G.mode =
        "explore";

    G.running =
        true;

    document.getElementById(
        "deathScreen"
    ).style.display =
        "none";

    document.getElementById(
        "battleScreen"
    ).style.display =
        "none";

    G.lastTime =
        performance.now();

    requestAnimationFrame(
        gameLoop
    );

    PG.updateHUD();

}


/* =========================================================
   INVESTIGATION SYSTEM
   ========================================================= */

function showInvestigation(
    clue
) {

    if (!clue) return;

    G.mode =
        "clue";

    const screen =
        document.getElementById(
            "clueScreen"
        );

    const content =
        document.getElementById(
            "clueContent"
        );

    content.innerHTML = "";

    const heading =
        document.createElement(
            "h2"
        );

    heading.textContent =
        "FIELD NOTE";

    content.appendChild(
        heading
    );

    const paragraph =
        document.createElement(
            "p"
        );

    paragraph.textContent =
        clue.text;

    content.appendChild(
        paragraph
    );

    const extra =
        document.createElement(
            "p"
        );

    extra.textContent =
        getClueLore(
            clue.id
        );

    content.appendChild(
        extra
    );

    screen.style.display =
        "flex";

    AudioSystem.tone(
        300,
        0.15,
        "triangle",
        0.035
    );

}


function getClueLore(id) {

    const lore = {

        bloodyClothes:
            "The jacket has a faded county forestry patch. The name sewn inside has been carefully cut away.",

        strangeTracks:
            "Whatever made these tracks was walking on two legs for part of the trail. Something dragged the other set behind it.",

        caveMarkings:
            "The scratches aren't random. Some form repeated vertical lines, almost like someone was counting days."

    };

    return (
        lore[id] ||
        "There is something wrong here."
    );

}


/* =========================================================
   CLOSE CLUE
   ========================================================= */

document
    .getElementById(
        "closeClue"
    )
    .addEventListener(
        "click",
        () => {

            document.getElementById(
                "clueScreen"
            ).style.display =
                "none";

            G.mode =
                "explore";

        }
    );


/* =========================================================
   CUTSCENE SYSTEM
   ========================================================= */

let currentCutscene = null;

let cutsceneIndex = 0;


function playCutscene(
    scenes,
    finished
) {

    if (
        !Array.isArray(
            scenes
        ) ||
        scenes.length === 0
    ) {

        if (finished)
            finished();

        return;

    }

    G.mode =
        "cutscene";

    currentCutscene =
        scenes;

    cutsceneIndex =
        0;

    const screen =
        document.getElementById(
            "cutscene"
        );

    screen.style.display =
        "flex";

    showCutsceneFrame();

}


function showCutsceneFrame() {

    const scene =
        currentCutscene[
            cutsceneIndex
        ];

    const text =
        document.getElementById(
            "cutsceneText"
        );

    text.textContent =
        scene.text;


    if (
        scene.sound
    ) {

        playSceneSound(
            scene.sound
        );

    }

}


function playSceneSound(
    sound
) {

    switch (sound) {

        case "creature":
            AudioSystem.creature();
            break;

        case "scare":
            AudioSystem.scare();
            break;

        case "noise":
            AudioSystem.noise(
                0.5,
                0.06
            );
            break;

        case "death":
            AudioSystem.death();
            break;

        default:
            AudioSystem.tone(
                100,
                0.2,
                "triangle",
                0.03
            );

    }

}


document
    .getElementById(
        "cutsceneButton"
    )
    .addEventListener(
        "click",
        advanceCutscene
    );


function advanceCutscene() {

    cutsceneIndex++;

    if (
        cutsceneIndex >=
        currentCutscene.length
    ) {

        finishCutscene();

        return;

    }

    showCutsceneFrame();

}


function finishCutscene() {

    document.getElementById(
        "cutscene"
    ).style.display =
        "none";

    G.mode =
        "explore";

    if (
        typeof G.cutsceneFinished ===
        "function"
    ) {

        const callback =
            G.cutsceneFinished;

        G.cutsceneFinished =
            null;

        callback();

    }

}


/* =========================================================
   CUSTOM MONSTER DEATH CUTSCENES
   ========================================================= */

function playEnemyDeathScene(
    enemy
) {

    G.mode =
        "cutscene";

    AudioSystem.death();


    const scenes =
        getDeathScene(
            enemy
        );


    G.cutsceneFinished =
        () => {

            endBattleAfterDeath(
                enemy
            );

        };


    playCutscene(
        scenes
    );

}


function getDeathScene(
    enemy
) {

    switch (
        enemy.enemyType
    ) {


        /* -----------------------------------------
           WOLF
           ----------------------------------------- */

        case "wolf":

            return [

                {
                    text:
                        "The wolf staggers backward. Its growl fades into a frightened whine.",

                    sound:
                        "creature"

                },

                {
                    text:
                        "It disappears into the darkness between the trees. Only the disturbed leaves remain.",

                    sound:
                        "noise"

                },

                {
                    text:
                        "Something has been done to these animals. This wasn't natural.",

                    sound:
                        "noise"

                }

            ];


        /* -----------------------------------------
           SMILING DEER
           ----------------------------------------- */

        case "smilingDeer":

            return [

                {
                    text:
                        "The deer freezes. Its strange smile remains for a moment longer.",

                    sound:
                        "creature"

                },

                {
                    text:
                        "Its legs finally give out and it collapses beneath the trees.",

                    sound:
                        "death"

                },

                {
                    text:
                        "As you approach, you notice a faded number stamped into the underside of its collar.",

                    sound:
                        "noise"

                }

            ];


        /* -----------------------------------------
           BOAR
           ----------------------------------------- */

        case "rootedBoar":

            return [

                {
                    text:
                        "The enormous animal backs away, scraping the earth with one hoof.",

                    sound:
                        "creature"

                },

                {
                    text:
                        "It charges once more before stumbling and falling silent.",

                    sound:
                        "death"

                },

                {
                    text:
                        "Nearby, the ground is covered with strange roots that seem to lead toward the old research area.",

                    sound:
                        "noise"

                }

            ];


        /* -----------------------------------------
           LONG-EARED EXPERIMENT
           ----------------------------------------- */

        case "longEared":

            return [

                {
                    text:
                        "The creature suddenly stops fighting and stares directly at you.",

                    sound:
                        "scare"

                },

                {
                    text:
                        "For one second, it almost looks afraid.",

                    sound:
                        "noise"

                },

                {
                    text:
                        "Then it collapses into the undergrowth, leaving behind a torn identification tag.",

                    sound:
                        "death"

                }

            ];


        /* -----------------------------------------
           DEER MAN
           ----------------------------------------- */

        case "deerMan":

            return [

                {
                    text:
                        "The creature stands motionless. Its antlers scrape the cave ceiling.",

                    sound:
                        "creature"

                },

                {
                    text:
                        "A strange sound comes from its throat — somewhere between a sob and a laugh.",

                    sound:
                        "scare"

                },

                {
                    text:
                        "It slowly lowers its head.",

                    sound:
                        "noise"

                },

                {
                    text:
                        "The creature finally collapses, and the cave becomes completely silent.",

                    sound:
                        "death"

                },

                {
                    text:
                        "On the wall behind it, beneath years of scratches, you find a faded laboratory number.",

                    sound:
                        "noise"

                },

                {
                    text:
                        "PROJECT 07 — HUMAN / WILDLIFE ADAPTATION.",

                    sound:
                        "noise"

                }

            ];


        default:

            return [

                {
                    text:
                        "The creature falls still.",

                    sound:
                        "death"

                },

                {
                    text:
                        "The woods become quiet again.",

                    sound:
                        "noise"

                }

            ];

    }

}


/* =========================================================
   END BATTLE AFTER DEATH
   ========================================================= */

function endBattleAfterDeath(
    enemy
) {

    enemy.health =
        0;

    enemy.active =
        false;

    enemy.defeated =
        true;


    G.currentEnemy =
        null;

    G.battleOpen =
        false;

    G.mode =
        "explore";


    document.getElementById(
        "battleScreen"
    ).style.display =
        "none";


    P.stamina =
        Math.min(
            P.maxStamina,
            P.stamina + 20
        );


    PG.updateHUD();

}


/* =========================================================
   DEER MAN SPECIAL ENCOUNTER
   ========================================================= */

function spawnDeerMan() {

    const existing =
        enemies.find(
            enemy =>
                enemy.enemyType ===
                "deerMan"
        );


    if (existing)
        return existing;


    return PG.spawnMonster(
        "deerMan",
        3100,
        2500
    );

}


/* =========================================================
   MAKE DEER MAN APPEAR WHEN PLAYER
   GETS DEEP INTO THE WOODS
   ========================================================= */

const originalCheck =
    PG.Game;


let deerManTriggered =
    false;


setInterval(
    () => {

        if (
            !G.running ||
            G.mode !==
            "explore"
        ) {

            return;

        }


        if (
            deerManTriggered
        ) {

            return;

        }


        const d =
            Math.sqrt(

                Math.pow(
                    P.x - 3100,
                    2
                )

                +

                Math.pow(
                    P.y - 2500,
                    2
                )

            );


        if (
            d < 500
        ) {

            deerManTriggered =
                true;

            spawnDeerMan();

            showMessage(
                "S
